In [1]:
import torch

In [1]:
import polars as pl
import pandas as pd

In [15]:
data = pl.read_parquet("/sdd/Dubaoset/src/Phong/Model/data/trainClean/merged_data_part_0.parquet").to_pandas()

In [3]:
import numpy as np

In [4]:
singleBand = ['B09B','B10B','B11B','B12B','B14B','B16B','I2B','I4B','IRB','WVB']
diffBand= None
fullBand = singleBand + diffBand if diffBand is not None else singleBand

In [6]:
bandType = [
    f"{band}_t{i:+d}" if band != "Dem_value" else "Dem_value"
    for i in range(-6, 6)
    for band in fullBand
]

In [7]:
bandType

['B09B_t-6',
 'B10B_t-6',
 'B11B_t-6',
 'B12B_t-6',
 'B14B_t-6',
 'B16B_t-6',
 'I2B_t-6',
 'I4B_t-6',
 'IRB_t-6',
 'WVB_t-6',
 'B09B_t-5',
 'B10B_t-5',
 'B11B_t-5',
 'B12B_t-5',
 'B14B_t-5',
 'B16B_t-5',
 'I2B_t-5',
 'I4B_t-5',
 'IRB_t-5',
 'WVB_t-5',
 'B09B_t-4',
 'B10B_t-4',
 'B11B_t-4',
 'B12B_t-4',
 'B14B_t-4',
 'B16B_t-4',
 'I2B_t-4',
 'I4B_t-4',
 'IRB_t-4',
 'WVB_t-4',
 'B09B_t-3',
 'B10B_t-3',
 'B11B_t-3',
 'B12B_t-3',
 'B14B_t-3',
 'B16B_t-3',
 'I2B_t-3',
 'I4B_t-3',
 'IRB_t-3',
 'WVB_t-3',
 'B09B_t-2',
 'B10B_t-2',
 'B11B_t-2',
 'B12B_t-2',
 'B14B_t-2',
 'B16B_t-2',
 'I2B_t-2',
 'I4B_t-2',
 'IRB_t-2',
 'WVB_t-2',
 'B09B_t-1',
 'B10B_t-1',
 'B11B_t-1',
 'B12B_t-1',
 'B14B_t-1',
 'B16B_t-1',
 'I2B_t-1',
 'I4B_t-1',
 'IRB_t-1',
 'WVB_t-1',
 'B09B_t+0',
 'B10B_t+0',
 'B11B_t+0',
 'B12B_t+0',
 'B14B_t+0',
 'B16B_t+0',
 'I2B_t+0',
 'I4B_t+0',
 'IRB_t+0',
 'WVB_t+0',
 'B09B_t+1',
 'B10B_t+1',
 'B11B_t+1',
 'B12B_t+1',
 'B14B_t+1',
 'B16B_t+1',
 'I2B_t+1',
 'I4B_t+1',
 'IRB_t+1',
 'WVB_t+1',
 'B09B_t+2',
 'B10B_t+2',
 'B11B_t+2',
 'B12B_t+2',
 'B14B_t+2',
 'B16B_t+2',
 'I2B_t+2',
 'I4B_t+2',
 'IRB_t+2',
 'WVB_t+2',
 'B09B_t+3',
 'B10B_t+3',
 'B11B_t+3',
 'B12B_t+3',
 'B14B_t+3',
 'B16B_t+3',
 'I2B_t+3',
 'I4B_t+3',
 'IRB_t+3',
 'WVB_t+3',
 'B09B_t+4',
 'B10B_t+4',
 'B11B_t+4',
 'B12B_t+4',
 'B14B_t+4',
 'B16B_t+4',
 'I2B_t+4',
 'I4B_t+4',
 'IRB_t+4',
 'WVB_t+4',
 'B09B_t+5',
 'B10B_t+5',
 'B11B_t+5',
 'B12B_t+5',
 'B14B_t+5',
 'B16B_t+5',
 'I2B_t+5',
 'I4B_t+5',
 'IRB_t+5',
 'WVB_t+5']

In [11]:
arr = data.to_numpy()
# (rows, columns)
# 995228 rows × 120 columns

In [12]:
np.shape(arr)

(995228, 120)

In [17]:
from tqdm import tqdm

In [ ]:
# arr = arr.reshape(-1, 12, len(fullBand))
# -6 -> -1
# -5 -> 0

In [18]:
fullResult = []
newCols = [
    f"{band}_t{i:+d}" if band != "Dem_value" else "Dem_value"
    for i in range(-6, 0)
    for band in fullBand
] + ["output_0"]

for i in tqdm(range(0, 6)):
    period = [
        f"{band}_t{i:+d}" if band != "Dem_value" else "Dem_value"
        for i in range(i-6, i)
        for band in fullBand
    ]
    output = [f"output_{i}"]
    # lấy các cột cho 1 sample
    choosenData = data.loc[:, period + output]
    # Chuyển về numpy cho nhẹ 
    fullResult.extend(choosenData.to_numpy())
# sau do phai del data de giam bo nho
# Chuyển ngược về thành dataframe
fullResult = pd.DataFrame(fullResult, columns=newCols)

100%|██████████| 6/6 [01:46<00:00, 17.67s/it]

In [21]:
temp = data.loc[:, bandType].head(10)

In [24]:
temp[['B16B_t-3', 'B16B_t-2', 'B16B_t-1']]

     B16B_t-3    B16B_t-2    B16B_t-1
0  257.530212  257.965790  248.542831
1  270.648193  271.352509  271.889160
2  265.052765  265.193665  265.898163
3  264.877045  263.231537  261.195007
4  278.414978  278.160919  278.159088
5  268.815430  268.815430  268.953033
6  274.799988  274.540009  274.799988
7  239.146667  243.402222  245.798889
8  211.357498  208.966675  205.959961
9  219.786438  219.332153  221.895126

In [ ]:
fullResult[['B16B_t-3', 'B16B_t-2', 'B16B_t-1']]

           B16B_t-3    B16B_t-2    B16B_t-1
0        257.530212  257.965790  248.542831
1        270.648193  271.352509  271.889160
2        265.052765  265.193665  265.898163
3        264.877045  263.231537  261.195007
4        278.414978  278.160919  278.159088
...             ...         ...         ...
5971363  259.176331  259.820557  257.074554
5971364  203.943344  206.800003  208.170013
5971365  269.045105  268.908203  268.908203
5971366  263.873657  263.873657  263.873657
5971367  252.137985  250.988983  252.758987

[5971368 rows x 3 columns]

In [26]:
fullResult.head(10)

,B09B_t-6,B10B_t-6,B11B_t-6,B12B_t-6,B14B_t-6,B16B_t-6,I2B_t-6,I4B_t-6,IRB_t-6,WVB_t-6,...,B10B_t-1,B11B_t-1,B12B_t-1,B14B_t-1,B16B_t-1,I2B_t-1,I4B_t-1,IRB_t-1,WVB_t-1,output_0
0,224.706863,226.918503,231.041672,228.452133,229.276230,226.587311,228.407883,243.597427,231.525635,222.080750,...,241.716248,262.686798,249.989166,260.171997,248.542831,256.797974,276.496063,262.305756,228.150009,0.0
1,257.255219,262.356018,290.567505,268.533325,292.195984,272.157074,287.826782,296.063324,293.490051,249.716660,...,262.197998,290.177490,268.000000,291.766663,271.889160,287.363098,295.522827,292.875977,249.463333,0.0
2,244.965698,254.619995,283.787170,261.452698,284.672852,266.178619,280.621552,305.174500,286.299622,234.330017,...,254.431549,283.353821,261.303650,283.871002,265.898163,279.886902,305.173004,285.639313,234.125015,0.0
3,248.772827,256.820007,293.168640,267.914154,294.717010,270.587921,289.470886,302.251068,296.308105,239.463318,...,251.801392,283.375580,261.654419,282.857666,261.195007,277.587036,297.918976,285.448029,235.213974,0.0
4,261.642212,270.262482,292.691895,270.900024,295.157959,278.414978,293.594971,294.103333,294.809998,248.446274,...,269.621460,291.793488,270.298859,294.352539,278.159088,292.931091,293.390442,292.495056,248.939041,0.0
5,246.914307,256.998352,285.805359,262.906372,286.483551,268.539062,283.046875,290.252960,288.040955,235.109985,...,257.354980,284.748016,262.328186,286.032837,268.953033,283.288452,287.935730,287.281799,234.525009,0.0
6,253.187500,260.906006,292.978485,269.066650,294.949951,274.280029,290.455017,299.238647,296.109375,244.348190,...,261.554016,293.169098,269.066650,295.053955,274.799988,290.795715,298.975647,296.208740,245.493622,0.0
7,228.444977,234.530762,257.867004,248.146667,250.605988,236.194061,245.135010,279.912842,256.259277,222.378021,...,241.551636,269.387482,255.778015,262.994080,245.798889,256.931030,285.659973,268.746643,226.070007,0.0
8,212.549988,213.553345,212.857483,219.877991,211.109985,210.320007,210.038315,221.764984,212.482025,212.494995,...,208.510010,208.239990,217.341980,205.924011,205.959961,205.018005,217.219971,207.648010,207.503326,0.0
9,217.686646,218.821228,220.671997,225.038330,217.836670,216.018555,216.643341,231.015015,219.760010,215.892456,...,223.836044,225.780365,227.905457,224.054092,221.895126,223.153656,231.356323,225.019730,221.368286,0.0

In [22]:
len(fullResult)

5971368